# Generated by Django 5.0 on 2023-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='default_category_value', max_length=100),
        ),
    ]
